# Example classifier registration configuration

processing:
  name: "classifier"
  export_format: "pt"
  batch_size: 8
  mlflow_tracking_uri: "http://localhost:5000"
  dynamic: false

weights_path: models/classifier_demo.pt
