
classifier:
  weights_path: models/classifier_demo.pt
  processing:
    export_format: "pt"
    batch_size: 8
    dynamic: false

localizer:
  yolo:
    weights: models/best.pt
    imgsz: 640
    device: "cpu"
    conf_thres: 0.2
    iou_thres: 0.3
    max_det: 300
    overlap_metric: "IOU"
    task: "detect"
  mmdet: null
  processing:
    export_format: "pt"
    batch_size: 8
    dynamic: false

processing:
  name: "detector"
  mlflow_tracking_uri: "http://localhost:5000"
