# Quick-start detector visualization configuration
# Simple configuration for common use cases

# Dataset configuration
dataset_name: "savmap-train"
prediction_field: "detection_predictions"

# localizer configuration (at root level as expected by DetectionVisualizationConfig)
localizer:
  weights: models/best.pt
  imgsz: 800
  device: "cpu"
  conf_thres: 0.2
  iou_thres: 0.3
  max_det: 300
  overlap_metric: "IOU"

# classifier configuration (optional)
classifier_weights: checkpoints/classification/demo/best_classifier.pt

mlflow_alias: null
mlflow_name: null
mlflow_tracking_uri: "http://localhost:5000"
mlflow_dwnd_location: null

# processing configuration
batch_size: 8
debug: false
num_workers: 0
