# Quick-start detector visualization configuration
# Simple configuration for common use cases

# Dataset configuration
fiftyone:
  dataset_name: "savmap-train"
  prediction_field: "detection_predictions"

label_studio:
  url: "http://localhost:8080"
  api_key: "1234567890"
  project_id: 1
  model_tag: "version-demo"

# processing configuration
batch_size: 8
debug: false

mlflow:
  alias: demo
  name: detector
  tracking_uri: "http://localhost:5000"
  dwnd_location: null


# localizer configuration
localizer:
  weights: models/best.pt
  imgsz: 800
  device: "cpu"
  conf_thres: 0.2
  iou_thres: 0.3
  max_det: 300
  overlap_metric: "IOU"

# classifier configuration (optional)
classifier_weights: checkpoints/classification/demo/best_classifier.pt





