# Unified configuration for classification pipeline (train + eval)

# ----------------------
# Task
# ----------------------
task: classification

# ----------------------
# Model configuration
# ----------------------
model:
  backbone: timm/vit_small_patch16_224.dino
  pretrained: true
  backbone_source: timm
  dropout: 0.2
  freeze_backbone: true
  input_size: 224
  mean: [0.554, 0.469, 0.348]
  std: [0.203, 0.173, 0.144]

# ----------------------
# Dataset configuration
# ----------------------
dataset:
  root_data_directory: "D:/workspace/data/demo-dataset"
  single_class:
    enable : true
    background_class_name: "background"
    single_class_name: "wildlife"
    keep_classes: null
    discard_classes: ["vegetation", "termite mound", "rocks", "other", "label"]
  input_size: 224
  transforms:
    train:
      - name: Resize
        params:
          size: ${dataset.input_size}
      - name: RandomHorizontalFlip
        params:
          p: 0.5
      - name: ColorJitter
        params:
          brightness: 0.2
          contrast: 0.2
          saturation: 0.2
      - name: RandomRotation
        params:
          degrees: 45
    val:
      - name: Resize
        params:
          size: ${dataset.input_size}

# ----------------------
# Training configuration
# ----------------------
train:
  batch_size: 4
  epochs: 10
  lr: 0.0001
  threshold: 0.5 # classification threshold for Precision, Recall, F1Score
  label_smoothing: 0.0
  weight_decay: 0.0001
  lrf: 0.1
  precision: bf16-mixed
  accelerator: auto

eval:
  split: val  # 'val' or 'test'
  device: cpu  # or 'cuda'
  batch_size: 4

# ----------------------
# Checkpoint configuration
# ----------------------
checkpoint:
  monitor: val_f1score
  save_top_k: 1
  mode: max
  save_last: true
  dirpath: "checkpoints/classification"
  patience: 10
  save_weights_only: true
  filename: "best"
  min_delta: 0.001

# ----------------------
# MLflow configuration
# ----------------------
mlflow:
  experiment_name: wildtrain_classification
  run_name: demo
  log_model: true

# ----------------------
# DVC dataset tracking configuration
# ----------------------
track_dataset: false
dataset_name: "roi-demo" 