# Example configuration for classifier visualization

dataset_name: "my_classification_dataset"
checkpoint_path: "checkpoints/classification/best-model.ckpt"
prediction_field: "classification_predictions"
batch_size: 32
device: "cpu"
debug: false
