# ----------------------
# Train
# ----------------------
disable_train: false
train:
  config: D:\workspace\repos\wildtrain\configs\classification\classification_train.yaml
  debug: false

# ----------------------
# Eval
# ----------------------
disable_eval: true
eval:
  config: D:\workspace\repos\wildtrain\configs\classification\classification_eval.yaml
  debug: false

# ----------------------
# Output
# ----------------------
results_dir: results/classification