# Unified Classification Configuration
# This config demonstrates how to use the unified ClassificationDataModule
# with both ROI and crop dataset types

dataset:
  root_data_directory: D:\workspace\data\demo-dataset
  
  # Dataset type: "roi" for pre-computed crops, "crop" for dynamic crop extraction
  dataset_type: "crop"  # or "crop" or "roi" 

  curriculum_config:
    enabled: true
    type: "difficulty"
    difficulty_strategy: "linear"
    start_difficulty: 0.0
    end_difficulty: 1.0
    warmup_epochs: 0
    log_frequency: 10
  
  stats:
    mean: [0.554, 0.469, 0.348]
    std: [0.203, 0.173, 0.144]
  
  input_size: 224

  transforms:
    train:
      - name: Resize
        params:
          size: ${dataset.input_size}
      - name: RandomHorizontalFlip
        params:
          p: 0.5
      - name: ColorJitter
        params:
          brightness: 0.1
          contrast: 0.0
          saturation: 0.0
      - name: RandomRotation
        params:
          degrees: 45
    
    val:
      - name: Resize
        params:
          size: ${dataset.input_size}
  
  # ROI dataset parameters (used when dataset_type = "roi")
  single_class:
    enable: true
    background_class_name: "background"
    single_class_name: "wildlife"
    keep_classes: null
    discard_classes: ["rocks","vegetation","other","termite mound"]
  
  # Rebalancing
  rebalance: false
  
  # Crop dataset parameters (used when dataset_type = "crop")
  crop_size: 224
  max_tn_crops: 1
  p_draw_annotations: 0.0
  
  # Curriculum parameters (used when dataset_type = "crop")
  compute_difficulties: true
  preserve_aspect_ratio: true

model:
  backbone: timm/mobilenetv4_hybrid_large.ix_e600_r384_in1k
  pretrained: true
  backbone_source: timm
  dropout: 0.2
  freeze_backbone: true
  input_size: ${dataset.input_size}
  mean: ${dataset.stats.mean}
  std: ${dataset.stats.std}

train:
  batch_size: 64
  epochs: 20
  lr: 0.0001
  label_smoothing: 0.0
  weight_decay: 0.0001
  lrf: 0.1
  precision: bf16-mixed
  accelerator: auto

checkpoint:
  monitor: val_f1score
  save_top_k: 1
  mode: max
  save_last: true
  dirpath: checkpoints/classification
  patience: 10
  save_weights_only: true
  filename: "{epoch:02d}-{val_f1score:.2f}"
  min_delta: 0.001

mlflow:
  experiment_name: wildtrain_classification
  run_name: "unified_classifier"
  log_model: true


# DVC dataset tracking configuration
track_dataset: false
dataset_name: "roi-demo"
