# Example configuration for classifier visualization

dataset_name: "savmap-train"
checkpoint_path: checkpoints/classification/best_classifier.pt
prediction_field: "classification_predictions"
batch_size: 32
device: "cpu"
debug: true
