# Example configuration for WildTrain classification training
task: classification

run_name: "dinov2-small-3hiddenlayers"

dataset:
  root_data_directory: D:\PhD\workspace\data
  rebalance: true

  single_class:
    enable : true
    background_class_name: "background"
    single_class_name: "wildlife"
    keep_classes: null
    discard_classes: ["vegetation", "termite mound", "rocks", "other", "label","detection"]

  stats:
    mean:  [0.460, 0.440, 0.358]
    std:   [0.174, 0.153, 0.148]
  
  input_size: 224

  transforms:
    train:
      - name: RandomHorizontalFlip
        params:
          p: 0.5
      - name: ColorJitter
        params:
          brightness: 0.2
          contrast: 0.0
          saturation: 0.0
      - name: RandomZoomOut
        params:
          fill: [117, 112, 80]
          side_range : [1.0,4.0]
          p: 0.5
      - name: RandomAffine
        params:
          degrees: 45
          translate: [0.1, 0.3]
          scale: [0.9, 1.2]
          shear: 5
          fill: [117, 112, 80]
      - name: Resize
        params:
          size: ${dataset.input_size}

    val:
      - name: Resize
        params:
          size: ${dataset.input_size}

model:
  backbone: timm/vit_small_patch16_224.dino
  pretrained: true
  backbone_source: timm
  dropout: 0.2
  freeze_backbone: true
  input_size: ${dataset.input_size}
  mean: ${dataset.stats.mean}
  std: ${dataset.stats.std}

train:
  batch_size: 32
  epochs: 20
  lr: 0.001
  label_smoothing: 0.0
  weight_decay: 0.0001
  lrf: 0.01
  precision: bf16-mixed
  accelerator: auto

checkpoint:
  monitor: val_f1score
  save_top_k: 1
  mode: max
  save_last: true
  dirpath: "checkpoints/classification"
  patience: 10
  save_weights_only: true
  filename: "best"
  min_delta: 0.001

mlflow:
  experiment_name: wildtrain_classification
  run_name: ${run_name}
  log_model: true


# DVC dataset tracking configuration
track_dataset: false
dataset_name: "roi-demo" 
