# Example configuration file for wildata import_dataset command
# Usage: wildata import-dataset --config import-config-example.yaml

# Required parameters
source_path: D:\workspace\data\general_dataset\tiled-data\coco-dataset\annotations\annotations_train.json
source_format: "coco"  # or "yolo" "coco" "ls"
dataset_name: general_dataset

# Pipeline configuration
root: D:\workspace\data\demo-dataset
split_name: "train"  # train, val, or test
enable_dvc: false

# Processing options
processing_mode: "batch"  # streaming or batch
track_with_dvc: false
bbox_tolerance: 5

# Label Studio options (optional)
dotenv_path: ".env"  # "path/to/.env"
ls_xml_config: "configs/label_studio_config.xml"  # "path/to/label_studio_config.xml"
ls_parse_config: false

# ROI configuration (optional)
disable_roi: false # optional
roi_config:
  random_roi_count: 2
  roi_box_size: 384
  min_roi_size: 32
  dark_threshold: 0.7
  background_class: "background"
  save_format: "jpg"
  quality: 95
  sample_background: false


# Transformation pipeline configuration (optional)
transformations:
  enable_bbox_clipping: true
  bbox_clipping:
    tolerance: 5
    skip_invalid: false
  
  enable_augmentation: false
  augmentation:
    rotation_range: [-45, 45]
    probability: 1.0
    brightness_range: [-0.2, 0.4]
    scale: [1.0, 2.0]
    translate: [-0.1, 0.2]
    shear: [-5, 5]
    contrast_range: [-0.2, 0.4]
    noise_std: [0.01, 0.1]
    seed: 41
    num_transforms: 2
  
  enable_tiling: false
  tiling:
    tile_size: 800
    stride: 640
    min_visibility: 0.7
    max_negative_tiles_in_negative_image: 3
    negative_positive_ratio: 1.0
    dark_threshold: 0.5 