# ----------------------
# Train
# ----------------------
disable_train: false
train:
  config: configs\detection\yolo_configs\yolo.yaml
  debug: true

# ----------------------
# Eval
# ----------------------
disable_eval: false
eval:
  config: configs\detection\yolo_configs\yolo_eval.yaml
  debug: true

# ----------------------
# Output
# ----------------------
results_dir: results/yolo
