# Example YOLO evaluation configuration

# Path to the trained YOLO weights file
weights:
  localizer: D:/workspace/repos/wildtrain/models/best.pt
  classifier: null #D:/workspace/repos/wildtrain/models/best_classifier.pt

# Path to the data config YAML (YOLO format)
data: D:/workspace/repos/wildtrain/configs/detection/yolo_configs/data/demo.yaml

device: "cuda"  # Device to run the evaluation on (cuda/cpu)

metrics:
  average: macro # weighted, macro, micro
  class_agnostic: false

# Evaluation parameters
# 'eval' section is passed as eval_config to the evaluator
eval:
  imgsz: 640           # Image size for evaluation
  split: "val"           # Split to evaluate on
  iou: 0.6
  single_cls: true   # Treat dataset as single-class
  half: false
  batch_size: 8       # Batch size for DataLoader
  num_workers: 0       # Number of DataLoader workers (0 for Windows compatibility)
  rect: false          # Use rectangular batches
  stride: 32           # Model stride
  task: "detect"         # Task type (detect/classify/segment)
  classes: null        # Optionally restrict to specific class indices
  cache: false         # Use cache for images/labels
  multi_modal: false   # Not using multi-modal data
  conf: 0.1         # Confidence threshold for evaluation
  max_det: 300      # Maximum detections per image
  verbose: false    # Verbosity level
  augment: false        # Use Test Time Augmentation

